import os
from common.config import (
    KAFKA_BOOTSTRAP, KAFKA_TOPIC_RAW, KAFKA_TOPIC_ANOMALY, STARTING_OFFSETS,
    PG_URL, PG_USER, PG_PASSWORD, PG_TABLE,
    INFLUX_URL, INFLUX_ORG, INFLUX_BUCKET, INFLUX_TOKEN, INFLUX_PRECISION,
    MEASUREMENT_METRICS, MEASUREMENT_ANOMS,
    checkpoint_dir
)

APP_NAME = os.getenv("APP_NAME", "iot-anomaly-streaming")

KAFKA_TOPIC = os.getenv("KAFKA_TOPIC", KAFKA_TOPIC_RAW)
STARTING_OFFSETS = STARTING_OFFSETS

WINDOW_DURATION = os.getenv("WINDOW_DURATION", "1 minute")
WATERMARK_DELAY = os.getenv("WATERMARK_DELAY", "2 minutes")

Z_THRESHOLD = float(os.getenv("Z_THRESHOLD", "2.0"))
MIN_STD = float(os.getenv("MIN_STD", "0.05"))

CHECKPOINT_DIR = os.getenv("CHECKPOINT_DIR", checkpoint_dir("iot_anomaly_v2"))

WRITE_TO_POSTGRES = os.getenv("WRITE_TO_POSTGRES", "true").lower() == "true"
PG_URL = PG_URL
PG_USER = PG_USER
PG_PASSWORD = PG_PASSWORD
PG_TABLE = PG_TABLE

WRITE_TO_INFLUX = os.getenv("WRITE_TO_INFLUX", "true").lower() == "true"
INFLUX_URL = INFLUX_URL
INFLUX_ORG = INFLUX_ORG
INFLUX_BUCKET = INFLUX_BUCKET
INFLUX_TOKEN = INFLUX_TOKEN
INFLUX_PRECISION = INFLUX_PRECISION
MEASUREMENT_METRICS = MEASUREMENT_METRICS
MEASUREMENT_ANOMS = MEASUREMENT_ANOMS

WRITE_TO_KAFKA = os.getenv("WRITE_TO_KAFKA", "true").lower() == "true"
KAFKA_TOPIC_ANOMALY = os.getenv("KAFKA_TOPIC_ANOMALY", KAFKA_TOPIC_ANOMALY)

MAX_OFFSETS_PER_TRIGGER = int(os.getenv("MAX_OFFSETS_PER_TRIGGER", "1000"))